name: CI (master)

on:
  push:
    branches:
      - master
      - main
      - v[1-9]*
  pull_request:
    branches:
      - master
      - main
      - v[1-9]*

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
        matrix:
          os:
            - ubuntu-latest
            - windows-latest
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run clippy
      run: cargo clippy -- -D warnings
