name: Prepare draft

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  test-again:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v5
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target/release
          target/debug
          target/.rustc_info.json
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Test 
      run: cargo test --verbose --all-features
  prepare-draft:
    runs-on: ubuntu-latest
    needs:
      - test-again
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v5
    - name: Verify version in Cargo.toml
      run: |
        if ! fgrep -q "version = \"${{ github.ref_name }}\"" Cargo.toml; then
          echo "Version in Cargo.toml does not match tag name"
          exit 1
        fi
    - name: Create a Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        # The name of the tag. This should come from the webhook payload, `github.GITHUB_REF` when a user pushes a new tag
        tag_name: ${{ github.ref_name }}
        generate_release_notes: true
        draft: true
        token: ${{ secrets.GITHUB_TOKEN }}